//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDPKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuDatPhong
    {
        public int ID { get; set; }
        public Nullable<int> PhieuDatPhong_ID { get; set; }
        public Nullable<int> Phong_ID { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
    
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
