//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDPKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.AlbumAnh = new HashSet<AlbumAnh>();
            this.ChiTietDichVu = new HashSet<ChiTietDichVu>();
            this.ChiTietPhieuDatPhong = new HashSet<ChiTietPhieuDatPhong>();
            this.ChiTietTienNghi = new HashSet<ChiTietTienNghi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LoaiPhong_ID { get; set; }
        public string TenPhong { get; set; }
        public Nullable<long> Gia { get; set; }
        public Nullable<int> SLNguoi { get; set; }
        public string HinhAnhBia { get; set; }
        public string DTPhong { get; set; }
        public string MoTa { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumAnh> AlbumAnh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDichVu> ChiTietDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuDatPhong> ChiTietPhieuDatPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTienNghi> ChiTietTienNghi { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
